import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import aiRoutes from './routes/aiRoutes.js';
import lessonsRoutes from './routes/lessonsRoutes.js';
import subjectsRoutes from './routes/subjectsRoutes.js';
import authRoutes from './routes/authRoutes.js';
import teamRoutes from './routes/teamRoutes.js';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use('/api/ai', aiRoutes);
app.use('/api/lessons', lessonsRoutes);
app.use('/api/subjects', subjectsRoutes);
app.use('/api/auth', authRoutes);
app.use('/api/teams', teamRoutes);
const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`🚀 Server running with TypeScript at: http://localhost:${PORT}`);
});